config/routes.rb
Rails.application.routes.draw do
  resources :campaigns
  resources :advertisers
  resources :hosts
  post 'events/create' => 'events#create'
  root to: "hosts#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/advertiser.rb
class Advertiser < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/campaign.rb
class Campaign < ApplicationRecord
end

app/models/host.rb
class Host < ApplicationRecord
end

app/controllers/advertisers_controller.rb
class AdvertisersController < ApplicationController
  before_action :set_advertiser, only: [:show, :edit, :update, :destroy]

  # GET /advertisers
  # GET /advertisers.json
  def index
    @advertisers = Advertiser.all
  end

  # GET /advertisers/1
  # GET /advertisers/1.json
  def show
  end

  # GET /advertisers/new
  def new
    @advertiser = Advertiser.new
  end

  # GET /advertisers/1/edit
  def edit
  end

  # POST /advertisers
  # POST /advertisers.json
  def create
    @advertiser = Advertiser.new(advertiser_params)

    respond_to do |format|
      if @advertiser.save
        format.html { redirect_to @advertiser, notice: 'Advertiser was successfully created.' }
        format.json { render :show, status: :created, location: @advertiser }
      else
        format.html { render :new }
        format.json { render json: @advertiser.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /advertisers/1
  # PATCH/PUT /advertisers/1.json
  def update
    respond_to do |format|
      if @advertiser.update(advertiser_params)
        format.html { redirect_to @advertiser, notice: 'Advertiser was successfully updated.' }
        format.json { render :show, status: :ok, location: @advertiser }
      else
        format.html { render :edit }
        format.json { render json: @advertiser.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /advertisers/1
  # DELETE /advertisers/1.json
  def destroy
    @advertiser.destroy
    respond_to do |format|
      format.html { redirect_to advertisers_url, notice: 'Advertiser was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_advertiser
      @advertiser = Advertiser.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def advertiser_params
      params.require(:advertiser).permit(:name, :email, :phone_number, :stripe_customer_id)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/campaigns_controller.rb
class CampaignsController < ApplicationController
  before_action :set_campaign, only: [:show, :edit, :update, :destroy]

  # GET /campaigns
  # GET /campaigns.json
  def index
    @campaigns = Campaign.all
  end

  # GET /campaigns/1
  # GET /campaigns/1.json
  def show
  end

  # GET /campaigns/new
  def new
    @campaign = Campaign.new
  end

  # GET /campaigns/1/edit
  def edit
  end

  # POST /campaigns
  # POST /campaigns.json
  def create
    @campaign = Campaign.new(campaign_params)

    respond_to do |format|
      if @campaign.save
        format.html { redirect_to @campaign, notice: 'Campaign was successfully created.' }
        format.json { render :show, status: :created, location: @campaign }
      else
        format.html { render :new }
        format.json { render json: @campaign.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /campaigns/1
  # PATCH/PUT /campaigns/1.json
  def update
    respond_to do |format|
      if @campaign.update(campaign_params)
        format.html { redirect_to @campaign, notice: 'Campaign was successfully updated.' }
        format.json { render :show, status: :ok, location: @campaign }
      else
        format.html { render :edit }
        format.json { render json: @campaign.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /campaigns/1
  # DELETE /campaigns/1.json
  def destroy
    @campaign.destroy
    respond_to do |format|
      format.html { redirect_to campaigns_url, notice: 'Campaign was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_campaign
      @campaign = Campaign.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def campaign_params
      params.require(:campaign).permit(:name, :references, :clicks, :views)
    end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  skip_before_action :verify_authenticity_token
  
  def create
    puts "EVENT CREATION PARAMS: #{params}"
  end
end

app/controllers/hosts_controller.rb
class HostsController < ApplicationController
  before_action :set_host, only: [:show, :edit, :update, :destroy]

  # GET /hosts
  # GET /hosts.json
  def index
    @hosts = Host.all
  end

  # GET /hosts/1
  # GET /hosts/1.json
  def show
  end

  # GET /hosts/new
  def new
    @host = Host.new
  end

  # GET /hosts/1/edit
  def edit
  end

  # POST /hosts
  # POST /hosts.json
  def create
    @host = Host.new(host_params)

    respond_to do |format|
      if @host.save
        format.html { redirect_to @host, notice: 'Host was successfully created.' }
        format.json { render :show, status: :created, location: @host }
      else
        format.html { render :new }
        format.json { render json: @host.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /hosts/1
  # PATCH/PUT /hosts/1.json
  def update
    respond_to do |format|
      if @host.update(host_params)
        format.html { redirect_to @host, notice: 'Host was successfully updated.' }
        format.json { render :show, status: :ok, location: @host }
      else
        format.html { render :edit }
        format.json { render json: @host.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hosts/1
  # DELETE /hosts/1.json
  def destroy
    @host.destroy
    respond_to do |format|
      format.html { redirect_to hosts_url, notice: 'Host was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_host
      @host = Host.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def host_params
      params.require(:host).permit(:name, :domain, :active, :tier)
    end
end

app/helpers/advertisers_helper.rb
module AdvertisersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/campaigns_helper.rb
module CampaignsHelper
end

app/helpers/hosts_helper.rb
module HostsHelper
end

app/views/advertisers/_form.html.erb
<%= form_with(model: advertiser, local: true) do |form| %>
  <% if advertiser.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(advertiser.errors.count, "error") %> prohibited this advertiser from being saved:</h2>

      <ul>
      <% advertiser.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :advertiser_name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :advertiser_email %>
  </div>

  <div class="field">
    <%= form.label :phone_number %>
    <%= form.text_field :phone_number, id: :advertiser_phone_number %>
  </div>

  <div class="field">
    <%= form.label :stripe_customer_id %>
    <%= form.text_field :stripe_customer_id, id: :advertiser_stripe_customer_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/advertisers/edit.html.erb
<h1>Editing Advertiser</h1>

<%= render 'form', advertiser: @advertiser %>

<%= link_to 'Show', @advertiser %> |
<%= link_to 'Back', advertisers_path %>

app/views/advertisers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Advertisers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Phone number</th>
      <th>Stripe customer</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @advertisers.each do |advertiser| %>
      <tr>
        <td><%= advertiser.name %></td>
        <td><%= advertiser.email %></td>
        <td><%= advertiser.phone_number %></td>
        <td><%= advertiser.stripe_customer_id %></td>
        <td><%= link_to 'Show', advertiser %></td>
        <td><%= link_to 'Edit', edit_advertiser_path(advertiser) %></td>
        <td><%= link_to 'Destroy', advertiser, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Advertiser', new_advertiser_path %>

app/views/advertisers/new.html.erb
<h1>New Advertiser</h1>

<%= render 'form', advertiser: @advertiser %>

<%= link_to 'Back', advertisers_path %>

app/views/advertisers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @advertiser.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @advertiser.email %>
</p>

<p>
  <strong>Phone number:</strong>
  <%= @advertiser.phone_number %>
</p>

<p>
  <strong>Stripe customer:</strong>
  <%= @advertiser.stripe_customer_id %>
</p>

<%= link_to 'Edit', edit_advertiser_path(@advertiser) %> |
<%= link_to 'Back', advertisers_path %>

app/views/campaigns/_form.html.erb
<%= form_with(model: campaign, local: true) do |form| %>
  <% if campaign.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(campaign.errors.count, "error") %> prohibited this campaign from being saved:</h2>

      <ul>
      <% campaign.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :campaign_name %>
  </div>

  <div class="field">
    <%= form.label :references %>
    <%= form.text_field :references, id: :campaign_references %>
  </div>

  <div class="field">
    <%= form.label :clicks %>
    <%= form.number_field :clicks, id: :campaign_clicks %>
  </div>

  <div class="field">
    <%= form.label :views %>
    <%= form.number_field :views, id: :campaign_views %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/campaigns/edit.html.erb
<h1>Editing Campaign</h1>

<%= render 'form', campaign: @campaign %>

<%= link_to 'Show', @campaign %> |
<%= link_to 'Back', campaigns_path %>

app/views/campaigns/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Campaigns</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>References</th>
      <th>Clicks</th>
      <th>Views</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @campaigns.each do |campaign| %>
      <tr>
        <td><%= campaign.name %></td>
        <td><%= campaign.references %></td>
        <td><%= campaign.clicks %></td>
        <td><%= campaign.views %></td>
        <td><%= link_to 'Show', campaign %></td>
        <td><%= link_to 'Edit', edit_campaign_path(campaign) %></td>
        <td><%= link_to 'Destroy', campaign, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Campaign', new_campaign_path %>

app/views/campaigns/new.html.erb
<h1>New Campaign</h1>

<%= render 'form', campaign: @campaign %>

<%= link_to 'Back', campaigns_path %>

app/views/campaigns/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @campaign.name %>
</p>

<p>
  <strong>References:</strong>
  <%= @campaign.references %>
</p>

<p>
  <strong>Clicks:</strong>
  <%= @campaign.clicks %>
</p>

<p>
  <strong>Views:</strong>
  <%= @campaign.views %>
</p>

<%= link_to 'Edit', edit_campaign_path(@campaign) %> |
<%= link_to 'Back', campaigns_path %>

app/views/hosts/_form.html.erb
<%= form_with(model: host, local: true) do |form| %>
  <% if host.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(host.errors.count, "error") %> prohibited this host from being saved:</h2>

      <ul>
      <% host.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :host_name %>
  </div>

  <div class="field">
    <%= form.label :domain %>
    <%= form.text_field :domain, id: :host_domain %>
  </div>

  <div class="field">
    <%= form.label :active %>
    <%= form.check_box :active, id: :host_active %>
  </div>

  <div class="field">
    <%= form.label :tier %>
    <%= form.text_field :tier, id: :host_tier %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/hosts/edit.html.erb
<h1>Editing Host</h1>

<%= render 'form', host: @host %>

<%= link_to 'Show', @host %> |
<%= link_to 'Back', hosts_path %>

app/views/hosts/index.html.erb
<link rel="manifest" href="/manifest.json" />
<script src="https://cdn.onesignal.com/sdks/OneSignalSDK.js" async=""></script>
<script>
  var OneSignal = window.OneSignal || [];
  OneSignal.push(function() {
    OneSignal.init({
      appId: "ce403946-9935-4b95-89ed-d46e5ac6811e",
    });
  });
</script>

<p id="notice"><%= notice %></p>

<h1>HOMEPAGE BB</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Domain</th>
      <th>Active</th>
      <th>Tier</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @hosts.each do |host| %>
      <tr>
        <td><%= host.name %></td>
        <td><%= host.domain %></td>
        <td><%= host.active %></td>
        <td><%= host.tier %></td>
        <td><%= link_to 'Show', host %></td>
        <td><%= link_to 'Edit', edit_host_path(host) %></td>
        <td><%= link_to 'Destroy', host, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Host', new_host_path %>

app/views/hosts/new.html.erb
<h1>New Host</h1>

<%= render 'form', host: @host %>

<%= link_to 'Back', hosts_path %>

app/views/hosts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @host.name %>
</p>

<p>
  <strong>Domain:</strong>
  <%= @host.domain %>
</p>

<p>
  <strong>Active:</strong>
  <%= @host.active %>
</p>

<p>
  <strong>Tier:</strong>
  <%= @host.tier %>
</p>

<%= link_to 'Edit', edit_host_path(@host) %> |
<%= link_to 'Back', hosts_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Notifone</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>